import numpy as np
from matplotlib import pyplot as plt
n1 = np.arange(start=0, stop=7)
x = np.where(np.logical_and(n1 >= 0, n1 <= 6), n1/3, 0)
n2 = np.arange(start=-2, stop=3)
h = np.where(np.logical_and(n2 >= -2, n2 <= 2), 1, 0)
n_min = min(np.amin(n1), np.amin(n2))
n = np.arange(start=n_min, stop=n_min+n1.size+n2.size-2+1)
y = np.convolve(x, h)
plt.stem(n, y)
plt.title('DT convolution using convolve function')
plt.xlabel('n')
plt.ylabel('Value')
plt.savefig('FIG/p2ap.eps', format='eps')
plt.show()